### ISSUE TITLE
No animations when moving horizontally across the grid (3.14)

### ISSUE THREAD

**Issue by fowlslegs** [zakkak/workspace-grid-gnome-shell-extension#20]
When I move vertically through my grid, I see the standard GNOME animation--a blue up or down arrow in the desktop on the grid I've moved to. Don't get me wrong, there's a lot of room for improvement on that animation, but it's better than what happens when I move horizontally, which is the desktop I've moved to is grayed out in the grid display overlay.

Implementing left and right pointing blue arrows should be an easy fix. Better would be to come up with a more informative and elegant animation.

**Comment by zakkak** [comment]
First you need to enable *User themes* to have a consistent behavior in all the directions (see #19).  
Regarding the style, I believe this is a matter of taste and one can't make everybody happy (-: .

TBH It would be nice if *Workspace-grid* could just inherit the theme's style and adapt it, instead of overwriting it.

The original theme used to support the arrows as you say.  The problem is that if a theme uses different arrows, then it is really ugly when you end up with different arrows for up-down and right-left.  That's why I decided to go with a less informative style that does not use arrows.

Ideas, for more informative, animations are welcomed, as are pull requests that improve this extension in any possible way.

**Comment by fowlslegs** [comment]
So actually the problem is that I'm using a custom theme. If I have to choose between giving up Arc shell theme and dealing with an inconsistent grid size, I'll choose the latter. Gnome default shell theme is just not very attractive IMHO. Is there any way you could override custom theme settings to standardize everything or is that too much monkey patching?

Definitely don't have the GTK knowledge to make a PR on this one.

>The original theme used to support the arrows as you say. The problem is that if a theme uses different arrows, then it is really ugly when you end up with different arrows for up-down and right-left. That's why I decided to go with a less informative style that does not use arrows.

The thing about this comment is that when I *don't* use a custom theme, the grid size is static *and* I get the correct directional arrow for each movement. I was talking about the move up, down, left, right a single desktop commands, not the move to desktop X command, which does not show an arrow, which is what I now believe you are talking about with this comment. Or not?

**Comment by zakkak** [comment]
What version of workspace grid are you using?

**Comment by zakkak** [comment]
bump
